version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.26
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: e_global_zone
      MYSQL_USER: yju_IAC_ADMIN
      MYSQL_PASSWORD: yju_IAC_5630
      MYSQL_ROOT_PASSWORD: yju_IAC_5630
      SERVICE_TAGS: dev
      # SERVICE_TAGS: service
      SERVICE_NAME: mysql
      TZ: "Asia/Seoul"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "9000:9000"
    networks:
      - laravel